#!/usr/bin/env bash

projname="$1"
if [[ -z "$projname" ]]; then
	echo "usage: $(basename "$0") <project-name>"
	exit 1
fi
if [[ -d "$projname" ]]; then
	echo "Error: $projname is a directory."
	exit 1
elif [[ -f "$projname" ]]; then
	read -rn 1 -p "$projname already exists. Overwrite? (y/n): " choice
	echo ""
	[[ "$choice" =~ ^[yY]([eE][sS])?$ ]] || exit 0
fi
cat <<EOF > "$projname"
#!/usr/bin/env bash
EOF
chmod +x "$projname"
echo "Successfully initialized $projname."
