#!/usr/bin/env bash

set -Eeuo pipefail

score=0
rounds=10

randint() {
	[[ "$#" == 2 ]] || {
		echo "Usage: randint <min> <max>" >&2
		return 1
	}
	local min="$1"
	local max="$2"
	local re='^-?[0-9]+$'
	if ! [[ "$min" =~ $re ]] || ! [[ "$max" =~ $re ]]; then
		echo "Error: Arguments must be integers." >&2
		return 1
	fi
	if (( min > max )); then
		echo "Error: Min cannot be greater than Max." >&2
		return 1
	fi
	echo $(( RANDOM % (max - min + 1) + min ))
}

game_test() {
	(( score += $(randint 1 10) ))
}

play_session() {
	score=0
	local game_pool=(
		"game_test"
	)
	local session_list=$(printf "%s\n" "${game_pool[@]}" | shuf -n "$rounds")
	local count=1
	for current_game in "$session_list"; do
		clear
		echo "game $count of $rounds."
		echo "Current score: $score."
		$current_game
		(( count++ ))
	done
	clear
	echo "Game over. Total score: $score."
	echo "Press any key to exit."
	read -rsn 1
	exit 0
}

show_intro() {
	clear
	cat <<-EOF
	Welcome to TermaGames, a small collection of Bash minigames.
	To start playing, press enter. To exit, press escape.
	EOF
}

show_intro
while true; do
	IFS= read -rsn 1 key
	case "$key" in
		"")
			play_session
			;;
		$'\e')
			echo "Goodbye."
			exit 0
			;;
	esac
done
