#!/usr/bin/env bash

set -Eeuo pipefail

randint() {
	[[ "$#" == 2 ]] || {
		echo "Usage: randint <min> <max>" >&2
		return 1
	}
	local min="$1"
	local max="$2"
	local re='^-?[0-9]+$'
	if ! [[ "$min" =~ $re ]] || ! [[ "$max" =~ $re ]]; then
		echo "Error: Arguments must be integers." >&2
		return 1
	fi
	if (( min > max )); then
		echo "Error: Min cannot be greater than Max." >&2
		return 1
	fi
	echo $(( RANDOM % (max - min + 1) + min ))
}

show_help() {
	clear
	cat <<-EOF
	The goal: Survive 10 rounds of random challenges, accumulating points along the way.
	Accumulate the highest score possible to win.
	Press any key to return to the menu...
	EOF
	read -rsn 1
	show_intro
}

show_intro() {
	clear
	cat <<-EOF
	Welcome to TermaGames, a small collection of Bash minigames.
	For instructions, press h. To start playing, press enter. To exit, press escape.
	EOF
}

show_intro
while true; do
	IFS= read -rsn 1 key
	case "$key" in
		"")
			randint 1 10
			;;
		$'\e')
			echo "Goodbye."
			exit 0
			;;
		[hH])
			show_help
			;;
		*)
			;;
	esac
done
