#!/usr/bin/env bash
set -euo pipefail

[[ "$EUID" -ne 0 ]] && echo "Please run as root." && exit 1
xbps-install -S
xbps-install -u xbps
xbps-install -u
if xbps-query -l | grep -q "linux[0-9]"; then
	current_kernel=$(uname -r | cut -d'.' -f1-2)
	kernels=(/boot/vmlinuz-*)
	latest_kernel=$(printf '%s\n' "${kernels[@]}" | sort -V | tail -n 1 | grep -oP '(?<=vmlinuz-)\d+\.\d+')
	if [[ "$current_kernel" != "$latest_kernel" ]]; then
		echo -e "\n[!] A new kernel is installed. Consider rebooting."
	fi
fi
